spring:
  datasource:
    url: jdbc:mysql://10.249.1.251:3306/demo?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
druid:
  username: admin
  password: 123456